[workspace]
members = [
    "common",
    "programs/solana-account-model",
    "programs/solana-instructions"
]
[workspace.dependencies]
anyhow = "1.0.100"
tokio = "1.48.0"
solana-client = "3.0.7"
solana-commitment-config = "3.0.0"
solana-sdk = "3.0.0"