[package]
name = "solana-transactions"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
anyhow.workspace = true
solana-sdk.workspace = true
solana-client.workspace = true
solana-commitment-config.workspace = true
solana-system-interface.workspace = true

